sudo: false
language: ruby
rvm:
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_install: gem install bundler
script:
  - bundle exec rake
  - bundle exec rubocop
env:
  - PUSHER_INSTANCE_ID=1b880590-6301-4bb5-b34f-45db1c5f5644
    PUSHER_SECRET_KEY=abc

